---
- hosts: all
  become: ture

  tasks:
  - name: creating docker image using docker command
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: create tag to image
    command: docker tag simple-devops-image boriphuth/simple-devops-image

  - name: push image to dockerhub
    command: docker push boriphuth/simple-devops-image

  - name: remove docker images from ansible server
    command: docker rmi simple-devops-image:latest boriphuth/simple-devops-image
    ignore_errors: yes
